config/routes.rb
Rails.application.routes.draw do
  root 'pins#index'

  get 'pins', to: 'pins#index'
  get 'pins/new', as: "new_pin"
  get 'pins/:id', to: 'pins#show', as: 'pin'
  get 'pins/:id/edit', to: 'pins#edit', as: 'edit_pin'
  post 'pins', to: 'pins#create'
  put 'pins/:id', to: 'pins#update'
  patch 'pins/:id', to: 'pins#update'
  delete 'pins/:id', to: 'pins#destroy'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :url, :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def index
  	@pins= Pin.all
  end

  def new
  	@pin = Pin.new
  end

##added notes from Elie lecture
  def create
  	@pin = Pin.new(pin_params)
  	@pin.save
  	if (@pin.save)
  		redirect_to pins_path
  	else
  		render :new
  	end
  end

  def show
  	@pin = Pin.find_by_id params[:id]
  end

  def edit
  	@pin = Pin.find_by_id params[:id]
  end

  def update
  	@pin = Pin.find_by_id params[:id]
  	redirect_to
  end

  def destroy
  	@pin = Pin.find_by_id params[:id]
  	@pin.destroy
  	redirect_to pins_path
  end

  private

  def pin_params
  	params.require(:pin).permit(:name, :url,:image,:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gpin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pins/edit.html.erb
<h1>Pins#edit</h1>
<p>Find me in app/views/pins/edit.html.erb</p>

app/views/pins/index.html.erb
<h1>All the Pins</h1>

<% @pins.each do |pin| %>
	<%= pin.name %> :<br />
	<%= link_to "Edit", edit_pin_path(pin)%>
	<%= pin.comment %> <br />
	<%= pin.url %> <br />
	<img src = "<%= pin.image %>" :<br />
<% end %>

<%= link_to "Add New Pin", new_pin_path%>

app/views/pins/new.html.erb
<h1>Add a new Pin</h1>

<!-- Added notes from lecture -->
<% if (@pin.errors.any?) %>
	<% @pin.errors.full_message.each do |error|%>
	<p style= "color:red;">
		<%= error%>
	</p>
	<%end %>
<%end %>



<%= form_for @pin do |f|%>
	<div>
		<%= f.label :name%>
		<%= f.text_field :name%>
	</div>
	<div>
		<%= f.label :url%>
		<%= f.text_field :url%>
	</div>
	<div>
		<%= f.label :comment%>
		<%= f.text_field :comment%>
	</div>
	<div>
		<%= f.label :image%>
		<%= f.text_field :image%>
	</div>
	<div>
		<%= f.submit%>
	</div>
<% end %>

app/views/pins/show.html.erb
<h1>Pins#show</h1>
<p>Find me in app/views/pins/show.html.erb</p>